[dependencies]
fs-extra = "10.1.0"
core = "1.0.113"
mongodb = "4.6.0"
express = "4.18.2"
snake-case = "3.0.4"
typescript = "5.1.3"
axios = "1.4.0"

[scripts]
build = "node build.js"
test = "node test.js"
start = "ts-node index.ts i"

[devDependncies]
typescript = "4.6.4"
